version: "3.2"
services:
    php:
        build: './php/'
        container_name: sbd_81_php
        volumes:
            - ./src/:/var/www/html/
        external_links:
            - mongo_default
    apache:
        build: './apache/'
        container_name: sbd_81_apache
        depends_on:
            - php
        ports:
            - "5001:80"
        volumes:
            - ./src/:/var/www/html/
            - ./apache/slr.apache.conf:/usr/local/apache2/conf/slr.apache.conf
        links:
            - php
networks:
    default:
        external:
            name: mongo_default
